version: 2.1
jobs:
  node_10:
    docker:
      - image: circleci/node:10.17
    steps:
      - checkout
      - run: yarn install --frozen-lockfile
      - run: yarn lint
      - run: yarn build
      - run: yarn test
  node_11:
    docker:
      - image: circleci/node:11.15
    steps:
      - checkout
      - run: yarn install --frozen-lockfile
      - run: yarn lint
      - run: yarn build
      - run: yarn test
workflows:
  all:
    jobs:
      - node_11
      - node_10
